a: &a
  controller: player
  action: menu
aa:
  <<: *a
  action: show

b: &b
  controller: bag
  action: menu
ba:
  <<: *b
  action: list
bb:
  <<: *b
  action: effect

h:
  controller: application
  action: menu

q:
  controller: application
  action: exit